module.exports = {
  caseType:'approved_school_safety_response',
  initialState:'event_registered',
  states:['event_registered','evidence_validated','triage_recorded','threat_team_review','response_approved','containment_observed','notification_queued','notification_sent','notification_failed','recovery_verified','rollback_verified','closed'],
  createRoles:['safety_analyst','threat_team_lead'],
  assessmentRoles:['safety_analyst','threat_team_reviewer','response_reviewer'],
  auditRoles:['threat_team_lead','district_auditor','privacy_reviewer'],
  connectorRoles:['integration_operator','threat_team_lead'],
  evidenceKinds:['telemetry_manifest','source_integrity_record','rule_version','identity_system_receipt','evidence_digest','deduplication_report','triage_report','model_evaluation','drift_report','adversarial_test','threat_team_review','response_approval','containment_observation','notification_receipt','notification_failure','recovery_record','rollback_record'],
  requiredSignals:['telemetryVersion','sourceVersion','ruleVersion','modelVersion','policyVersion','safetyLimitsVerified','sourceIntegrity','dedupStatus','precision','recall','falsePositiveRate','timeToDetectSeconds','timeToRespondSeconds','driftScore','adversarialPassRate','severityEvidence'],
  professionalBoundary:'Deterministic triage supports trained school safety teams. The system never dispatches responders, isolates systems, locks doors, sends emergency messages, diagnoses students, or makes a final threat determination.',
  connectors:[
    {name:'telemetry_scanner',purpose:'read-only signed telemetry and scanner receipts'},
    {name:'identity_sis',purpose:'minimal authorized identity and SIS references'},
    {name:'ticketing',purpose:'case ownership and disposition receipts'},
    {name:'notification',purpose:'approved mass-notification delivery receipts'},
    {name:'response_cad',purpose:'read-only responder acknowledgement receipts; dispatch prohibited'},
    {name:'evidence_storage',purpose:'tamper-evident encrypted evidence pointers'},
    {name:'access_control',purpose:'read-only status and rollback verification receipts'},
  ],
  transitions:[
    {from:'event_registered',action:'validate_evidence',to:'evidence_validated',roles:['safety_analyst','threat_team_reviewer'],requiresEvidence:true},
    {from:'evidence_validated',action:'record_triage',to:'triage_recorded',roles:['safety_analyst'],requiresEvidence:true},
    {from:'triage_recorded',action:'submit_threat_team_review',to:'threat_team_review',roles:['threat_team_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'threat_team_review',action:'approve_response_plan',to:'response_approved',roles:['threat_team_lead','response_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'response_approved',action:'record_containment_observation',to:'containment_observed',roles:['response_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'containment_observed',action:'queue_notification',to:'notification_queued',roles:['threat_team_lead'],requiresEvidence:true,dualControl:true},
    {from:'notification_queued',action:'record_notification',to:'notification_sent',roles:['integration_operator'],requiresEvidence:true},
    {from:'notification_queued',action:'record_notification_failure',to:'notification_failed',roles:['integration_operator'],requiresEvidence:true},
    {from:'notification_failed',action:'verify_recovery',to:'recovery_verified',roles:['response_reviewer','threat_team_lead'],requiresEvidence:true,dualControl:true},
    {from:'containment_observed',action:'verify_rollback',to:'rollback_verified',roles:['response_reviewer','threat_team_lead'],requiresEvidence:true,dualControl:true},
    {from:'notification_sent',action:'close_case',to:'closed',roles:['threat_team_lead','district_auditor'],requiresEvidence:true},
    {from:'recovery_verified',action:'close_case',to:'closed',roles:['threat_team_lead','district_auditor'],requiresEvidence:true},
    {from:'rollback_verified',action:'close_case',to:'closed',roles:['threat_team_lead','district_auditor'],requiresEvidence:true},
  ],
  acceptedFixture:{telemetryVersion:'t1',sourceVersion:'s1',ruleVersion:'r1',modelVersion:'m1',policyVersion:'p1',safetyLimitsVerified:true,sourceIntegrity:'verified',dedupStatus:'passed',precision:0.95,recall:0.95,falsePositiveRate:0.03,timeToDetectSeconds:20,timeToRespondSeconds:90,driftScore:0.02,adversarialPassRate:0.98,severityEvidence:'corroborated'},
  rejectedFixture:{telemetryVersion:'t1',sourceVersion:'s1',ruleVersion:'r1',modelVersion:'m1',policyVersion:'p1',safetyLimitsVerified:true,sourceIntegrity:'verified',dedupStatus:'passed',precision:0.6,recall:0.95,falsePositiveRate:0.03,timeToDetectSeconds:20,timeToRespondSeconds:90,driftScore:0.02,adversarialPassRate:0.98,severityEvidence:'corroborated'},
  readyDisposition:'trained_threat_team_review_required',
  holdDisposition:'quality_drift_source_or_safety_hold',
  decisionField:'responseCommand',
  assess:(x)=>{const precision=Number(x.precision),recall=Number(x.recall),fpr=Number(x.falsePositiveRate),ttd=Number(x.timeToDetectSeconds),ttr=Number(x.timeToRespondSeconds),drift=Number(x.driftScore),adversarial=Number(x.adversarialPassRate);const ready=x.safetyLimitsVerified===true&&x.sourceIntegrity==='verified'&&x.dedupStatus==='passed'&&precision>=0.9&&recall>=0.9&&fpr<=0.05&&ttd<=60&&ttr<=300&&drift<=0.05&&adversarial>=0.95&&x.severityEvidence==='corroborated';return{disposition:ready?'trained_threat_team_review_required':'quality_drift_source_or_safety_hold',responseCommand:null,metrics:{precision,recall,falsePositiveRate:fpr,timeToDetectSeconds:ttd,timeToRespondSeconds:ttr,driftScore:drift,adversarialPassRate:adversarial},versions:{telemetry:x.telemetryVersion,source:x.sourceVersion,rules:x.ruleVersion,model:x.modelVersion}};},
};
